name: Update GitHub Pages every hour

on:
  schedule:
    - cron: '5 * * * *'  # Run every 6 hours at minute 0

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run Python script
        run: python main.py
